services:
    App\domain\repository\CartRepository:
        alias: App\data\repository\CartRepositoryImpl;


    App\data\repository\CartRepositoryImpl:
        autowire: true
        autoconfigure: true

    App\application\usecase\AddCartItem:
        autowire: true
        autoconfigure: true

    App\application\usecase\ViewCart:
        autowire: true
        autoconfigure: true

    App\application\usecase\DeleteCartItem:
        autowire: true
        autoconfigure: true
